import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
menus = [{"description":"Cadastro - FAQ","categoria":"Central de Comunica\u00e7\u00f5es","menu_category_id":"6","route":"\/main\/faq","route_back":"\/faq","menu_order":"1","menu_category_order":"1"},{"description":"FAQ","categoria":"Central de Comunica\u00e7\u00f5es","menu_category_id":"6","route":"\/main\/faq-view","route_back":"\/faq-view","menu_order":"2","menu_category_order":"1"},{"description":"Folha de Rosto","categoria":"Avalia\u00e7\u00e3o","menu_category_id":"5","route":"\/main\/cover-sheet","route_back":"cover-sheet","menu_order":"1","menu_category_order":"2"},{"description":"Manual do Avaliador","categoria":"Avalia\u00e7\u00e3o","menu_category_id":"5","route":"\/main\/evaluator-manual","route_back":"\/evaluator-manual","menu_order":"2","menu_category_order":"2"},{"description":"Provas","categoria":"Avalia\u00e7\u00e3o","menu_category_id":"5","route":"\/main\/exams","route_back":"\/exams","menu_order":"3","menu_category_order":"2"},{"description":"Lista de Verifica\u00e7\u00e3o","categoria":"Avalia\u00e7\u00e3o","menu_category_id":"5","route":"\/main\/verification-list","route_back":"\/verification-list","menu_order":"4","menu_category_order":"2"},{"description":"Avalia\u00e7\u00e3o Pr\u00e1tica","categoria":"Avalia\u00e7\u00e3o","menu_category_id":"5","route":"\/main\/pratical-evaluation-list","route_back":"pratical-evaluation-list","menu_order":"5","menu_category_order":"2"},{"description":"Convites","categoria":"Cadastros","menu_category_id":"1","route":"\/main\/invitation","route_back":"invite","menu_order":"3","menu_category_order":"3"},{"description":"Matriz de refer\u00eancia","categoria":"Cadastros","menu_category_id":"1","route":"\/main\/reference-matrix","route_back":"import-matrices","menu_order":"6","menu_category_order":"3"},{"description":"Central de Comunica\u00e7\u00e3o","categoria":"Cadastros","menu_category_id":"1","route":"\/main\/communication-center","route_back":"\/communication-center","menu_order":"9","menu_category_order":"3"},{"description":"Minha prepara\u00e7\u00e3o","categoria":"Central de Prepara\u00e7\u00e3o","menu_category_id":"4","route":"\/main\/preparation-central","route_back":"preparation-central","menu_order":"1","menu_category_order":"4"},{"description":"Cadastros (Docs., Videos e Testes)","categoria":"Central de Prepara\u00e7\u00e3o","menu_category_id":"4","route":"\/main\/register-media","route_back":"register-media","menu_order":"2","menu_category_order":"4"}];
}
